/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "tiny_combinatorial.v:5" *)
module main(a, b, c, d, e, f);
  (* src = "tiny_combinatorial.v:9" *)
  wire _0_;
  (* src = "tiny_combinatorial.v:6" *)
  input a;
  (* src = "tiny_combinatorial.v:6" *)
  input b;
  (* src = "tiny_combinatorial.v:6" *)
  input c;
  (* src = "tiny_combinatorial.v:6" *)
  input d;
  (* src = "tiny_combinatorial.v:6" *)
  input e;
  (* src = "tiny_combinatorial.v:7" *)
  output f;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h1e)
  ) _1_ (
    .I0(d),
    .I1(e),
    .I2(_0_),
    .I3(1'h0),
    .O(f)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h80)
  ) _2_ (
    .I0(a),
    .I1(b),
    .I2(c),
    .I3(1'h0),
    .O(_0_)
  );
endmodule
